- name: "gaming"
  block:

  # Potreba dstranit komnetar pro multilib
  # - name: "🎮 enable lib32 pkgs"
  #   ansible.builtin.replace:
  #     path: /etc/pacman.conf
  #     regexp: "^\\#[multilib]"
  #     replace: "\\[multilib]"
  #   become: true
  #   become_user: root
  #   become_method: sudo

  - name: "📦 installing a packages (lutris)"
    community.general.pacman:
      name: 
        - "lib32-nvidia-utils"
        - "nvidia-settings"
        - "vulkan-icd-loader"
        - "lib32-vulkan-icd-loader"
      state: present
    become: true
    become_user: "root"

  - name: "📦 installing a packages (wine)"
    community.general.pacman:
      name: 
        - "wine-staging"
        - "giflib"
        - "lib32-giflib"
        - "gnutls"
        - "lib32-gnutls"
        - "v4l-utils"
        - "lib32-v4l-utils"
        - "libpulse"
        - "lib32-libpulse"
        - "alsa-plugins"
        - "lib32-alsa-plugins"
        - "alsa-lib"
        - "lib32-alsa-lib"
        - "sqlite"
        - "lib32-sqlite"
        - "libxcomposite"
        - "lib32-libxcomposite"
        - "ocl-icd"
        - "lib32-ocl-icd"
        - "libva"
        - "lib32-libva"
        - "gtk3"
        - "lib32-gtk3"
        - "gst-plugins-base-libs"
        - "lib32-gst-plugins-base-libs"
        - "vulkan-icd-loader"
        - "lib32-vulkan-icd-loader"
        - "sdl2"
        - "lib32-sdl2"
      state: present
    become: true
    become_user: "root"

  - name: ✅ check and install an 📦 {{ item }}
    ansible.builtin.command: yay -S --answerclean Y --answerdiff N --noconfirm --noprogressbar {{ item }}
    loop:
      - bottles
    when: item not in installed_packages.stdout
