- name: "Fonts"
  block:
    - name: "📦 installing an package"
      community.general.pacman:
        name:
          - fontconfig
        state: present

    - name: 🍪 Gather installed packages
      ansible.builtin.command: pacman -Q
      register: installed_packages

    - name: ✅ check and install an 📦 {{ item }}
      ansible.builtin.command: yay -S --answerclean Y --answerdiff N --noconfirm --noprogressbar {{ item }}
      loop:
        - ttf-jetbrains-mono-nerd 
        - ttf-jetbrains-mono 
        - ttf-droid 
        - adobe-source-code-pro-fonts 
        - noto-fonts-emoji 
        - ttf-firacode 
        - ttf-font-awesome 
        - otf-font-awesome 
        - nerd-fonts-git 
        - ttf-sarasa-gothic-nerd-fonts 
        - ttf-sarasa-gothic-sc 
      when: item not in installed_packages.stdout

    - name: "🖨️ copying a dotfiles"
      shell: "stow -d {{ ansible_dotfiles }} -S fonts"
