- name: "Fonts"
  block:
    - name: "[INSTALL] - fontconfig"
      community.general.pacman:
        name:
          - fontconfig
        state: present

    - name: "[INSTALL] - ttf-sarasa-gothic-sc"
      shell:
        cmd: "yay -S --answerclean Y --answerdiff N --noconfirm --noprogressbar ttf-sarasa-gothic-sc"
      become: true
      become_user: spuxy

    - name: "[INSTALL] - ttf-sarasa-gothic-nerd-fonts"
      shell:
        cmd: "yay -S --answerclean Y --answerdiff N --noconfirm --noprogressbar ttf-sarasa-gothic-nerd-fonts"
      become: true
      become_user: spuxy

    - name: "[INSTALL] - nerd-fonts-git"
      shell:
        cmd: "yay -S --answerclean Y --answerdiff N --noconfirm --noprogressbar nerd-fonts-git"
      become: true
      become_user: spuxy

    - name: "[INSTALL] - otf-font-awesome"
      shell:
        cmd: "yay -S --answerclean Y --answerdiff N --noconfirm --noprogressbar otf-font-awesome"
      become: true
      become_user: spuxy

    - name: "[INSTALL] - ttf-font-awesome"
      shell:
        cmd: "yay -S --answerclean Y --answerdiff N --noconfirm --noprogressbar ttf-font-awesome"
      become: true
      become_user: spuxy

    - name: "[CREATE DIRECTORY] - Nerd fonts"
      ansible.builtin.file:
        path: "{{ ansible_home }}/pkgs/nerd-fonts"
        state: directory

    - name: "[STOW] - fontconfig"
      shell: "stow -d {{ ansible_dotfiles }} -S fonts"
