- name: "GTK"
  block:
  - name: "📦 installing a packages"
    community.general.pacman:
      name:
        - "gtk3"
        - "gtk4"
        - "gtk-engine-murrine"
      state: present
    become: true
    become_user: 'root'
    become_method: 'sudo'

  - name: "🖨️ Copying an dotfiles"
    shell: "stow -d {{ ansible_dotfiles }} -S gtk3"

  - name: "🍪 Gather installed packages"
    ansible.builtin.command: pacman -Q
    register: installed_packages

  - name: ✅ check and install an 📦 {{ item }}
    ansible.builtin.command: yay -S --answerclean Y --answerdiff N --noconfirm --noprogressbar {{ item }}
    loop:
      - colloid-gruvbox-gtk-theme-git 
      - colloid-gruvbox-theme-git 
      - colloid-catpuccino-gtk-theme-git 
      - colloid-catpuccino-theme-git 
      - colloid-everforest-gtk-theme-git 
      - colloid-everforest-theme-git 
      - colloid-dracula-gtk-theme-git 
      - colloid-dracula-theme-git 
      - colloid-nord-gtk-theme-git 
      - colloid-nord-icon-theme-git 
      - colloid-icon-theme-git 
      - colloid-cursors-git 
      - colloid-gtk-theme-git 
    when: item not in installed_packages.stdout
