- name: "Hyprland"
  block:
    - name: "📦 installing an packages"
      community.general.pacman:
        name:
          [
            "brightnessctl",
            "btop",
            "eog",
            "fastfetch",
            "gnome-system-monitor",
            "mousepad",
            "mpv-mpris",
            "nvtop",
            "nwg-look",
            "nwg-shell",
            "pacman-contrib",
            "yt-dlp",
            "cliphist",
            "grim",
            "gvfs",
            "gvfs-mtp",
            "hypridle",
            "aquamarine",
            "hyprlock",
            "imagemagick",
            "inxi",
            "jq",
            "kitty",
            "nano",
            "network-manager-applet",
            "playerctl",
            "polkit-gnome",
            "python-requests",
            "python-pyquery",
            "qt5ct",
            "qt6ct",
            "qt6-svg",
            "slurp",
            "swappy",
            "swww",
            "wl-clipboard",
            "xdg-user-dirs",
            "xdg-utils",
            "xdg-desktop-portal-hyprland",
            "xdg-desktop-portal-gtk",
            "yad",
          ]
        state: present
      become: true
      become_user: "root"
      become_method: "sudo"

- name: "🧨 uninstall xdg-desktop-portal-wlr and xdg-desktop-portal-lxqt"
  community.general.pacman:
    name: ["xdg-desktop-portal-lxqt", "xdg-desktop-portal-wlr"]
    state: absent
  become: true
  become_user: "root"
  become_method: "sudo"

- name: ✅ check and install an 📦 {{ item }}
  ansible.builtin.command: yay -S --answerclean Y --answerdiff N --noconfirm --noprogressbar {{ item }}
  loop:
    # - nwg-shell
    - pyprland 
  when: item not in installed_packages.stdout

- name: "🖨️ coyping a dotfiles"
  shell: "stow -d {{ ansible_dotfiles }} -S fastfetch"

- name: "🖨️ coyping a dotfiles"
  shell: "stow -d {{ ansible_dotfiles }} -S kitty"
