- name: "Hyprland"
  block:
  - name: "INSTALL - Hyprland"
    community.general.pacman:
      name:
        - "gdb"
        - "ninja"
        - "gcc"
        - "cmake"
        - "meson"
        - "libxcb"
        - "xcb-proto"
        - "xcb-util"
        - "xcb-util-keysyms"
        - "libxfixes"
        - "libx11"
        - "libxcomposite"
        - "xorg-xinput"
        - "libxrender"
        - "pixman"
        - "wayland-protocols"
        - "cairo"
        - "pango"
        - "seatd"
        - "libxkbcommon"
        - "xcb-util-wm"
        - "xorg-xwayland"
        - "libinput"
        - "libliftoff"
        - "libdisplay-info"
        - "cpio"
        - "tomlplusplus"
        - "hyprlang"
        - "hyprcursor"
        - "hyprwayland-scanner"
        #- "xcb-utils-errors"
      executable: yay
      state: present

  - name: "GIT CLONE - Hyprland"
    ansible.builtin.git:
      repo: "https://github.com/hyprwm/Hyprland"
      dest: "{{ ansible_home }}/pkgs/Hyprland"
      recursive: true

  - name: "BUILD - Hyprland"
    shell: 
      chdir: "{{ ansible_home }}/pkgs/Hyprland"
      cmd: "make all && sudo make install"

  - name: "STOW - Hyprland"
    shell: "stow -d {{ ansible_dotfiles }} -S hyprland"
