- name: "Hyprland"
  block:
  - name: "isntalling an hyprland"
    community.general.pacman:
      name:
        - "gdb"
        - "ninja"
        - "gcc"
        - "cmake"
        - "meson"
        - "libxcb"
        - "xcb-proto"
        - "xcb-util"
        - "xcb-util-keysyms"
        - "libxfixes"
        - "libx11"
        - "libxcomposite"
        - "xorg-xinput"
        - "libxrender"
        - "pixman"
        - "wayland-protocols"
        - "cairo"
        - "pango"
        - "seatd"
        - "libxkbcommon"
        - "xcb-util-wm"
        - "xorg-xwayland"
        - "libinput"
        - "libliftoff"
        - "libdisplay-info"
        - "cpio"
        - "tomlplusplus"
        - "hyprlang"
        - "hyprcursor"
        - "hyprwayland-scanner"
        - "hyprutils"
        #- "xcb-utils-errors"
      executable: yay
      state: present


  - name: check if Hyprland binary exists
    stat:
      path: "/usr/local/bin/Hyprland"
    register: hyprland_bin

  - name: "git cloning an hypr's repo"
    ansible.builtin.git:
      repo: "https://github.com/hyprwm/Hyprland"
      dest: "{{ ansible_home }}/Pkgs/Hyprland"
      recursive: true
    when: not hyprland_bin.stat.exists

  - name: "building an hyprland"
    shell: 
      chdir: "{{ ansible_home }}/Pkgs/Hyprland"
      cmd: "make all && sudo make install"
    when: not hyprland_bin.stat.exists

  - name: "copying a dotfiles"
    shell: "stow -d {{ ansible_dotfiles }} -S hyprland"
