- name: Test
  hosts: localhost
  vars:
    - ansible_user: "spuxy"
    - ansible_dotfiles: "/home/spuxy/.dotfiles"
    - ansible_home: "/home/spuxy"
    - ansible_personal_scripts: "/home/spuxy/.local/share/bin"
    - ansible_zsh: "/home/spuxy/.config/zsh"
    - ansible_pkgs: "/home/spuxy/pkgs"
  tasks:
    - name: Full System Upgrade
      community.general.pacman:
        upgrade: true
      become: true
      become_user: root
      become_method: sudo

    - include_tasks: ./plugins/stow.yml

    - include_tasks: ./sddm.yml

    - include_tasks: ./pipewire.yml
    - include_tasks: ./neovim.yml
    - include_tasks: ./wallust.yml
    - include_tasks: ./swaync.yml
    - include_tasks: ./productivity-tools.yml
    # Pre-task
    - include_tasks: ./stow.yml

    # Languages
    - include_tasks: ./go.yml
    - include_tasks: ./rust.yml
    - include_tasks: ./npm.yml


    - include_tasks: ./yay.yml
    - include_tasks: ./fonts.yml
    # Tools
    - include_tasks: ./alacritty.yml
    - include_tasks: ./atuin.yml

    - include_tasks: ./bottom.yml

    - include_tasks: ./colorls.yml
    - include_tasks: ./calcurse.yml
    - include_tasks: ./conky.yml

    - include_tasks: ./discordo.yml
    - include_tasks: ./dunst.yml

    - include_tasks: ./eww.yml

    - include_tasks: ./fzf.yml

    - include_tasks: ./git.yml
    - include_tasks: ./gtk.yml

    - include_tasks: ./hyprland.yml

    - include_tasks: ./lf.yml

    - include_tasks: ./mpd.yml
    - include_tasks: ./mpv.yml

    - include_tasks: ./ncmpcpp.yml
    - include_tasks: ./neofetch.yml
    - include_tasks: ./npm.yml
    - include_tasks: ./nvidia.yml

    - include_tasks: ./pacman.yml
    - include_tasks: ./picom.yml
    - include_tasks: ./polybar.yml

    - include_tasks: ./qutebrowser.yml

    - include_tasks: ./ranger.yml
    - include_tasks: ./redshift.yml
    - include_tasks: ./rofi.yml
    - include_tasks: ./russ.yml

    - include_tasks: ./scripts.yml
    # - include_tasks: ./spotify-tui.yml
    - include_tasks: ./spotifyd.yml
    - include_tasks: ./sxhkd.yml
    - include_tasks: ./sddm.yml
    - include_tasks: ./swaync.yml

    - include_tasks: ./tmux.yml

    # - include_tasks: ./xinitrc.yml

    - include_tasks: ./zathura.yml
    - include_tasks: ./zsh.yml
    - include_tasks: ./zoxide.yml

    # Dirs
    - include_tasks: ./dirs.yml
    - include_tasks: ./books.yml

