- name: "NEOVIM"
  block:
  - name: "installing an neovim"
    community.general.pacman:
      name:
        - "neovim"
      state: present
    become: true
    become_user: 'root'
    become_method: 'sudo'

  - name: check if dot.vim exists
    stat:
      path: "{{ ansible_home }}/.config/nvim"
    register: nvim_dir

  - name: "git cloning an dot.vim repo"
    ansible.builtin.git:
      repo: "https://github.com/Spuxy/dot.vim.git"
      dest: "{{ ansible_home }}/.config/nvim"
    become: true
    become_user: 'root'
    become_method: 'sudo'
    when: not nvim_dir.stat.exists
