- name: "NVIDIA"
  block:
  - name: "🎮 installing an nvidia"
    community.general.pacman:
      name:
        - "{{ pkg1 }}"
        - "{{ pkg2 }}"
        - "{{ pkg3 }}"
        - "{{ pkg4 }}"
      state: present

  - name: "🎮 building kernel parameters into initramfs"
    ansible.builtin.replace:
      path: /etc/mkinitcpio.conf
      regexp: "^MODULES\\=\\(\\)"
      replace: "MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)"
    become: true
    become_user: root
    become_method: sudo

  - name: "🎮 create nvidia.conf for options"
    lineinfile:
      path: /etc/modprobe.d/nvidia.conf
      line: "options nvidia_drm modeset=1 fbdev=1"
      create: true
    become: true
    become_user: root
    become_method: sudo

  - name: "🎮 building initramfs"
    command: mkinitcpio -P
    become: true
    become_user: root
    become_method: sudo

  vars:
    pkg1: "nvidia"
    pkg2: "nvidia-utils"
    pkg3: "nvidia-settings"
    pkg4: "egl-wayland"

