- name: "Pipewire"
  block:
    - name: "installation sounds pkgs"
      community.general.pacman:
        name:
          [
            "pipewire",
            "pipewire-pulse",
            "pipewire-audio",
            "pipewire-alsa",
            "wireplumber",
            "pavucontrol",
            "pamixer",
          ]
        state: present
      become: true
      become_user: "root"
      become_method: "sudo"

- name: "enable systemd pipewire.socket"
  ansible.builtin.systemd_service:
    name: "pipewire.socket"
    state: started
    enabled: true
    scope: user
  become: true
  become_user: "{{ ansible_user }}"

- name: "enable systemd pipewire.service"
  ansible.builtin.systemd_service:
    name: "pipewire.service"
    enabled: true
    scope: user
  become: true
  become_user: "{{ ansible_user }}"

- name: "enable systemd pipewire-pulse.service"
  ansible.builtin.systemd_service:
    name: "pipewire-pulse.service"
    enabled: true
    scope: user
  become: true
  become_user: "{{ ansible_user }}"

- name: "enable systemd pipewire-pulse.socket"
  ansible.builtin.systemd_service:
    name: "pipewire-pulse.socket"
    enabled: true
    scope: user
  become: true
  become_user: "{{ ansible_user }}"

- name: "enable systemd wireplumber.service"
  ansible.builtin.systemd_service:
    name: "wireplumber.service"
    enabled: true
    scope: user
  become: true
  become_user: "{{ ansible_user }}"
