- name: Install packages
  community.general.pacman:
    name:
      [
        "termshark",
        "wireshark-qt",
        "gimp",
        "xclip",
        "screenkey",
        "tldr",
        "ripgrep",
        "fd",
        "fzf",
        "wget",
        "jq",
        "curl",
        "discord",
        "bottom",
        "calcurse",
      ]
    state: present
  become: true
  become_user: 'root'
  become_method: 'sudo'

- name: Install packages
  ansible.builtin.pip:
    name: howdoi
  become: true
  become_user: 'root'
  become_method: 'sudo'
