- name: Install packages
  community.general.pacman:
    name:
      [
        "termshark",
        "wireshark-qt",
        "gimp",
        "xclip",
        "screenkey",
        "tldr",
        "ripgrep",
        "fd",
        "fzf",
        "wget",
        "jq",
        "curl",
        "discord",
        "bottom",
        "calcurse",
      ]
    state: present
  become: true
  become_user: 'root'
  become_method: 'sudo'


- name: check if howdoi binary exists
  stat:
    path: "/usr/bin/howdoi"
  register: howdoi_bin

- name: "isntalling an howdoi"
  shell:
    cmd: "yay -S --answerclean Y --answerdiff N --noconfirm --noprogressbar howdoi"
  become: true
  become_user: spuxy
  when: not howdoi_bin.stat.exists
