- name: "📦 installing a packages"
  community.general.pacman:
    name:
      [
        "screenkey",
        "tldr",
        # reading/notes
        "obsidian",
        "zathura",
        # media
        "gimp",
        "discord",
        "firefox",
        "kodi",
        # network debugging
        "nmap",
        "wget",
        "jq",
        "curl",
        "termshark",
        "wireshark-qt",
        # files manipulation
        "zip",
        "unzip",
        "ripgrep",
        "fd",
        "fzf",
        "xclip",
        # process debugging
        "lsof",
        "rsync",
        "strace",
        "bottom",
      ]
    state: present
  become: true
  become_user: 'root'
  become_method: 'sudo'

- name: "🍪 Gather installed packages"
  ansible.builtin.command: pacman -Q
  register: installed_packages

- name: "✅ Check and install 📦 {{ item }}"
  ansible.builtin.command: yay -S --answerclean Y --answerdiff N --noconfirm --noprogressbar {{ item }}
  become: true
  become_user: '{{ ansible_user }}'
  loop:
    - 1password
    - ferdium
    - vesktop-bin  
  when: item not in installed_packages.stdout
