- name: "SDDM"
  block:
  - name: "[INSTALL] - sddm"
    community.general.pacman:
      name:
        - "{{ pkg1 }}"
        - "{{ pkg2 }}"
        - "{{ pkg3 }}"
        - "{{ pkg4 }}"
      state: present
    become: true
    become_user: "root"
    become_method: "sudo"

  - name: "[SYSTEMD] enable sddm"
    ansible.builtin.systemd_service:
      name: sddm.service
      state: started
      enabled: true
    become: true
    become_user: "{{ ansible_user }}"

  - name: "[CREATE DIRECTORY] sddm.conf.d"
    ansible.builtin.file:
      path: "/etc/sddm.conf.d"
      state: directory
    become: yes
    become_user: root
    become_method: sudo

  - name: "[CREATE DIRECTORY] wayland-sessions"
    ansible.builtin.file:
      path: "/usr/share/wayland-sessions"
      state: directory
    become: yes
    become_user: root
    become_method: sudo

  - name: "[CHECK] dir exists for sddm theme"
    stat: path=/usr/share/sddm/themes/dot.sddm
    register: theme_dir

  - name: "[STOW] - theme sddm"
    shell:
      chdir: "{{ ansible_home }}/.dotfiles/sddm"
      cmd: "stow -t /usr/share/sddm/themes theme"
    when: not theme_dir.stat.exists

  - name: "[CHECK] dir exists for wayland session"
    stat: path=/usr/share/wayland-sessions
    register: wayland_sesion_dir

  - name: "[STOW] - wayland-session sddm"
    shell:
      chdir: "{{ ansible_home }}/.dotfiles/sddm"
      cmd: "stow -t /usr/share/wayland-sessions wayland-sessions"
    when: not wayland_sesion_dir.stat.exists

  - name: "[CHECK] dir exists for sddm conf.d"
    stat: path=/etc/sddm.conf.d
    register: sddm_conf_dir

  - name: "[STOW] - sddm"
    shell:
      chdir: "{{ ansible_home }}/.dotfiles/sddm"
      cmd: "stow -t /etc/sddm.conf.d sddm.conf.d"
    when: not sddm_conf_dir.stat.exists

  vars:
    pkg1: "sddm"
    pkg2: "qt6-5compat"
    pkg3: "qt6-declarative"
    pkg4: "qt6-svg" 
