- name: "Swww"
  block:
  - name: "git cloning an repo"
    ansible.builtin.git:
      repo: "https://github.com/LGFae/swww.git"
      dest: "{{ ansible_home }}/Pkgs/swww"

  - name: check if swww bin exists
    stat:
      path: "/usr/bin/swww"
    register: swww_bin

  - name: check if swww-daemon bin exists
    stat:
      path: "/usr/bin/swww-daemon"
    register: swwwdaemon_bin

  - name: "building an pkg"
    shell: 
      chdir: "{{ ansible_home }}/Pkgs/swww"
      cmd: "cargo build --release"
    become: true
    become_user: "{{ ansible_user }}"
    when: not swww_bin.stat.exists

  - name: "move swww binary into /usr/bin"
    shell: 
      chdir: "{{ ansible_home }}/Pkgs/swww/target/release"
      cmd: "mv swww /usr/bin"
    become: true
    become_user: 'root'
    become_method: 'sudo'
    when: not swww_bin.stat.exists

  - name: "move swww-daemon binary into /usr/bin"
    shell: 
      chdir: "{{ ansible_home }}/Pkgs/swww/target/release"
      cmd: "mv swww-daemon /usr/bin"
    become: true
    become_user: 'root'
    become_method: 'sudo'
    when: not swwwdaemon_bin.stat.exists
