- name: "virtualization"
  block:
    - name: "📦 installing a packages"
      community.general.pacman:
        name:
          - "libvirt"
          - "virt-manager"
          - "qemu"
          - "iptables-nft"
          - "dnsmasq"
          - "docker"
          - "docker-compose"
          - "kubectl"
          - "kind"
          - "helm"
        state: present

    - name: "🚨 enable systemd libvirtd.service"
      ansible.builtin.systemd_service:
        name: libvirtd.service
        state: started
        enabled: true
      become: true
      become_user: "{{ ansible_user }}"

    - name: "🚨 enable systemd virtlogd.service"
      ansible.builtin.systemd_service:
        name: virtlogd.service
        state: started
        enabled: true
      become: true
      become_user: "{{ ansible_user }}"

  ### group sudo usermod -aG libvirt {user}
    - name: "🔨 added user {{ ansible_user }} to 'libvirt' group"
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: libvirt
        append: yes

    - name: ✅ check and install an 📦 {{ item }}
      ansible.builtin.command: yay -S --answerclean Y --answerdiff N --noconfirm --noprogressbar {{ item }}
      loop:
        # - nwg-shell
        - kind 
      when: item not in installed_packages.stdout
