- name: "wallust"
  block:
  - name: "[GIT CLONE] - wallust"
    ansible.builtin.git:
      repo: "https://codeberg.org/explosion-mental/wallust.git"
      dest: "{{ ansible_home }}/pkgs/wallust"
      version: dev
    become: true
    become_user: '{{ ansible_user }}'

  - name: "[BUILD] - wallust"
    become: true
    become_user: 'root'
    become_method: 'sudo'
    shell: 
      chdir: '{{ ansible_home }}/pkgs/wallust'
      cmd: "make install"

