- name: "wlogout"
  block:
  - name: "📦 installing a packages"
    community.general.pacman:
      name:
        - "gobject-introspection"
        - "gtk-layer-shell"
        - "gtk3"
        - "meson"
        - "git"
        - "scdoc"
      state: present
    become: true
    become_user: 'root'
    become_method: 'sudo'

  - name: "✅ check and install an 📦 {{ item }}"
    ansible.builtin.command: yay -S --answerclean Y --answerdiff N --noconfirm --noprogressbar {{ item }}
    loop:
      - wlogout 
    when: item not in installed_packages.stdout

  - name: "🖨️ copying a dotfiles"
    shell: "stow -d {{ ansible_dotfiles }} -S wlogout"
