- name: "pipewire"
  block:
    - name: "📦 installing a packages"
      community.general.pacman:
        name:
          [
            "pipewire",
            "pipewire-pulse",
            "pipewire-audio",
            "pipewire-alsa",
            "wireplumber",
            "pavucontrol",
            "pamixer",
            "sof-firmware",
          ]
        state: present
      become: true
      become_user: "root"
      become_method: "sudo"

- name: "🚨 enable systemd pipewire.socket"
  ansible.builtin.systemd_service:
    name: "pipewire.socket"
    state: started
    enabled: true
    scope: user
  become: true
  become_user: "{{ ansible_user }}"

- name: "🚨 enable systemd pipewire-pulse.service"
  ansible.builtin.systemd_service:
    name: "pipewire-pulse.service"
    enabled: true
    scope: user
  become: true
  become_user: "{{ ansible_user }}"

- name: "🚨 enable systemd pipewire-pulse.socket"
  ansible.builtin.systemd_service:
    name: "pipewire-pulse.socket"
    enabled: true
    scope: user
  become: true
  become_user: "{{ ansible_user }}"

- name: "🚨 enable systemd wireplumber.service"
  ansible.builtin.systemd_service:
    name: "wireplumber.service"
    enabled: true
    scope: user
  become: true
  become_user: "{{ ansible_user }}"

- name: "🚨 enable systemd pipewire.service"
  ansible.builtin.systemd_service:
    name: "pipewire.service"
    enabled: true
    scope: user
  become: true
  become_user: "{{ ansible_user }}"

- name: "🧨 To be sure that pulse is deleted"
  community.general.pacman:
    name: ["pulseaudio", "pulseaudio-bluetooth", "pulseaudio-alsa"]
    state: absent
  become: true
  become_user: "root"
  become_method: "sudo"

- name: "✅ check if pulseaudio service exists"
  stat: path=/etc/systemd/pulseaudio.service
  register: pulseaudio_service

- name: "✅ check if pulseaudio service exists at user space"
  stat: path=/etc/systemd/user/pulseaudio.service
  register: pulseaudio_user_service

- name: "🚨 disable systemd pulseaudio.service"
  ansible.builtin.systemd_service:
    name: "pulseaudio.service"
    enabled: false
    scope: user
  become: true
  become_user: "{{ ansible_user }}"
  when: pulseaudio_service.stat.exists or pulseaudio_user_service.stat.exists

- name: "🚨 disable systemd pulseaudio.socket"
  ansible.builtin.systemd_service:
    name: "pulseaudio.socket"
    enabled: false
    scope: user
  become: true
  become_user: "{{ ansible_user }}"
  when: pulseaudio_service.stat.exists or pulseaudio_user_service.stat.exists
